server {
    listen 8080;
    server_name _;

    access_log /dev/stdout;
    error_log /dev/stderr notice;

    location = /healthz {
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    location / {
        default_type text/plain;
        return 200 "unicron demo web\n";
    }
}
